stages:
  - test

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml

vet:
  stage: test
  image: golang:1.20
  script:
    go vet .

tests:
  stage: test
  image: golang:1.20
  script:
    go test -coverprofile=coverage
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 1 day
